### ISSUE TITLE
nyc example

### ISSUE THREAD

**Issue by corysimmons** [codecov/example-node#5]
please?

**Comment by stevepeak** [comment]
What is a "nyc"?

**Comment by corysimmons** [comment]
https://github.com/bcoe/nyc

https://github.com/sindresorhus/ava#code-coverage

**Comment by jimthedev** [comment]
nyc is the best way to use babel 6 with mocha and code coverage. It wraps istanbul so that it doesn't break w/babel 6. We use it in commitizen with codecov. You can check out [our package.json](https://github.com/commitizen/cz-cli/blob/78c8a083d67346ad1bbab2cf0ebc43d833f976da/package.json#L12) for a full example. My PR above adds an example to the readme.

**Comment by cryptoquick** [comment]
Was just looking for this.

**Comment by corysimmons** [comment]
Cool thanks @jimthedev
